- hosts: web
  tasks:
   - name: install httpd
     yum:
       name: httpd
       state: installed


   - name: create  index.html page
     copy:
         content: "Welcome Ansible Training"
         dest: /var/www/html/index.html

   - name: change port number  httpd.conf
     lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 8080

   - name: add port 8080 into firewall
     firewalld:
         port: 8080/tcp
         permanent: yes
         state: enabled
         immediate: true

   - name: start httpd
     service: 
        name: httpd
        state: started
        enabled: true 

 
